# Placeholder for docker-compose.yml

version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    runtime: nvidia  # This line replaces the deploy section
